In [22]:
import numpy as np
import rioxarray

In [23]:
CHELSA_DIR = "/shares/wegner.ics.uzh/CHELSA/Future_Climatologies/"

In [24]:
refras =  rioxarray.open_rasterio(CHELSA_DIR + "tifs/CHELSA_gfdl-esm4_r1i1p1f1_w5e5_ssp585_tasmin_07_2071_2100_norm.tif", cache=False)
ys = refras.y
xs = refras.x

In [25]:
lsm = np.load(CHELSA_DIR + "lsm.npy")
lsm = lsm.T.astype(bool)
lsm[ys<-63] = False
print(lsm.shape)

(20880, 43200)


In [32]:
pcs = np.stack(np.where(lsm))

In [33]:
print(pcs.shape)
print(pcs[:, :5])

(2, 222613755)
[[   45    45    45    45    45]
 [17586 17587 17588 17589 17590]]


In [34]:
pcs = np.stack([ys[pcs[0]], xs[pcs[1]]]).T

In [35]:
print(pcs.shape)
print(pcs[:, :5])

(222613755, 2)
[[ 83.62069375 -33.44597281]
 [ 83.62069375 -33.43763948]
 [ 83.62069375 -33.42930614]
 ...
 [-62.99597233 -56.17097272]
 [-62.99597233 -56.16263938]
 [-62.99597233 -56.15430605]]


In [36]:
np.save(CHELSA_DIR + "point_to_coord.npy", pcs)